### PR TITLE
Added german translation and added country name support

### PR DESCRIPTION
**Pull request by beckerr-rzht**
* Added german translation

* Added support for country name as translation key.
  Currently in use are "de", "en", "fr" and "nb".
  See:
  ```
  wget -qO - https://static.eduvpn.nl/disco/institute_access.json \
	| jq '.instances[].display_name' | awk -F: '/:/{print $1}' | sort -u
  ```

* Institution list is sorted after(!) display name translations now.

### CODE REVIEW

**Comment by fkooman** [comment]
Thanks for the PR! Will look at it soon and make a new release!

**Comment by fkooman** [comment]
@dzolnai did you manage to look at this PR?

**Comment by dzolnai** [comment]
Hello @beckerr-rzht,

Sorry for taking this long to respond to you about your PR, but we thought it would be better if we would include the strings after we release version 2.
Otherwise we would end up with a version which has missing strings. Could you update your PR to match the latest version?
Also your edit to `SerializerService`  should be moved to `TranslatableString`.

**Comment by dzolnai** [comment]
Closing because #386 has fixed this

**Pull request closed without merging**
