### PR TITLE
KB -> kB

### PR DESCRIPTION
**Pull request by fkooman**

### CODE REVIEW

**Comment by dzolnai** [comment]
Technically it should KB because that means it is 1024 bytes, while kB means 1000 bytes.
But I agree that kB is more pleasing to the eye, and it doesn't really matter.

**Comment by fkooman** [comment]
Okay, maybe then we should really fix it! You don't have to approve everything! :-)

image

https://en.wikipedia.org/wiki/Kibibyte

What do you think? So we'd change all of them... also MiB etc.

**Comment by dzolnai** [comment]
We could divide by 1000 and then the labels would be correct. MiB would just confuse users.

**Comment by fkooman** [comment]
it seems Android also uses KB,MB,GB. Not sure if it is uses 1024 or 1000.

**Comment by fkooman** [comment]
I guess it depends on what mobile providers use when counting your data usage.

**Comment by fkooman** [comment]
it seems OpenVPN for Android uses kB in the status drawer... sigh :)

**Pull request merged**
