### PR TITLE
add release build script

### PR DESCRIPTION
**Pull request by fkooman**

### CODE REVIEW

**Comment by dzolnai** [comment]
How does this relate to the build script already in the repo?

**Comment by fkooman** [comment]
The (my) plan was to have two build scripts: 

1. Build from git branch/tag
2. Build from source tarball (from GH releases page where I upload fully cloned including submodules source of the app)

The first one we have, this PR adds the 2nd one.

**Comment by dzolnai** [comment]
Could you add some documentation about this to readme, and also rename the file? Release is not the best word for the source tarball.

**Comment by fkooman** [comment]
Done. Sorry I did this in the master branch :cry:

**Pull request merged**
