### PR TITLE
#309 Add new public keys

### PR DESCRIPTION
**Pull request by dzolnai**

### CODE REVIEW

**Comment by fkooman** [comment]
I'd just put those keys in actual code and not in that ridiculous Gradle format, prevent shooting yourself in the foot :)

**Comment by dzolnai** [comment]
If you would mess up the format, it will be a compile error.
By making it a build property, you can change it per flavor.

**Comment by fkooman** [comment]
You tested compiling? I'll make a new release then and tag it/publish it after you merge this.

**Comment by dzolnai** [comment]
Yes I did.

**Pull request merged**
