### PR TITLE
Update common

### PR DESCRIPTION
**Pull request by jwijenbergh**
Updates common, building and change file

### CODE REVIEW

**Review by dzolnai — APPROVED** [review]

**Comment by dzolnai** [comment]
Can you rebase your PR to fix the failing tests @jwijenbergh?

**Comment by jwijenbergh** [comment]
Done! Also bumped common again :)

**Comment by dzolnai** [comment]
And it's green! 🎉  Merging

**Comment by jwijenbergh** [comment]
Thanks Dániel!

**Pull request merged**
